# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/ui/build_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuildNewDialog(object):
    def setupUi(self, BuildNewDialog):
        BuildNewDialog.setObjectName("BuildNewDialog")
        BuildNewDialog.resize(708, 300)
        self.gridLayout = QtWidgets.QGridLayout(BuildNewDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.texture_pack_select = QtWidgets.QPushButton(BuildNewDialog)
        self.texture_pack_select.setObjectName("texture_pack_select")
        self.gridLayout.addWidget(self.texture_pack_select, 4, 2, 1, 1)
        self.repo_custom_name = QtWidgets.QLineEdit(BuildNewDialog)
        self.repo_custom_name.setText("")
        self.repo_custom_name.setObjectName("repo_custom_name")
        self.gridLayout.addWidget(self.repo_custom_name, 2, 1, 1, 2)
        self.l_texture_pack = QtWidgets.QLabel(BuildNewDialog)
        self.l_texture_pack.setObjectName("l_texture_pack")
        self.gridLayout.addWidget(self.l_texture_pack, 4, 0, 1, 1)
        self.l_custom_name = QtWidgets.QLabel(BuildNewDialog)
        self.l_custom_name.setObjectName("l_custom_name")
        self.gridLayout.addWidget(self.l_custom_name, 2, 0, 1, 1)
        self.model_pack_folder = QtWidgets.QLineEdit(BuildNewDialog)
        self.model_pack_folder.setReadOnly(True)
        self.model_pack_folder.setObjectName("model_pack_folder")
        self.gridLayout.addWidget(self.model_pack_folder, 3, 1, 1, 1)
        self.l_model_pack = QtWidgets.QLabel(BuildNewDialog)
        self.l_model_pack.setObjectName("l_model_pack")
        self.gridLayout.addWidget(self.l_model_pack, 3, 0, 1, 1)
        self.b_continue = QtWidgets.QPushButton(BuildNewDialog)
        self.b_continue.setObjectName("b_continue")
        self.gridLayout.addWidget(self.b_continue, 5, 1, 1, 2)
        self.texture_pack_folder = QtWidgets.QLineEdit(BuildNewDialog)
        self.texture_pack_folder.setReadOnly(True)
        self.texture_pack_folder.setObjectName("texture_pack_folder")
        self.gridLayout.addWidget(self.texture_pack_folder, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.model_pack_select = QtWidgets.QPushButton(BuildNewDialog)
        self.model_pack_select.setObjectName("model_pack_select")
        self.gridLayout.addWidget(self.model_pack_select, 3, 2, 1, 1)
        self.l_now_building = QtWidgets.QLabel(BuildNewDialog)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.l_now_building.setFont(font)
        self.l_now_building.setAlignment(QtCore.Qt.AlignCenter)
        self.l_now_building.setObjectName("l_now_building")
        self.gridLayout.addWidget(self.l_now_building, 0, 0, 1, 1)
        self.l_build_what = QtWidgets.QLabel(BuildNewDialog)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.l_build_what.setFont(font)
        self.l_build_what.setAlignment(QtCore.Qt.AlignCenter)
        self.l_build_what.setObjectName("l_build_what")
        self.gridLayout.addWidget(self.l_build_what, 0, 1, 1, 2)

        self.retranslateUi(BuildNewDialog)
        self.model_pack_select.clicked.connect(BuildNewDialog.pick_model_pack_folder) # type: ignore
        self.texture_pack_select.clicked.connect(BuildNewDialog.pick_texture_pack_folder) # type: ignore
        self.b_continue.clicked.connect(BuildNewDialog.b_continue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BuildNewDialog)

    def retranslateUi(self, BuildNewDialog):
        _translate = QtCore.QCoreApplication.translate
        BuildNewDialog.setWindowTitle(_translate("BuildNewDialog", "Build New Instance"))
        self.texture_pack_select.setText(_translate("BuildNewDialog", "Browse"))
        self.l_texture_pack.setText(_translate("BuildNewDialog", "Pick a Texture Pack folder (Optional)"))
        self.l_custom_name.setText(_translate("BuildNewDialog", "Type A Name for your build"))
        self.l_model_pack.setText(_translate("BuildNewDialog", "Pick a model pack folder (optional)"))
        self.b_continue.setText(_translate("BuildNewDialog", "Continue"))
        self.model_pack_select.setText(_translate("BuildNewDialog", "Browse"))
        self.l_now_building.setText(_translate("BuildNewDialog", "Now Building:"))
        self.l_build_what.setText(_translate("BuildNewDialog", "Nothing Yet"))
