# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/ui/building.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuildSucceededDialog(object):
    def setupUi(self, BuildSucceededDialog):
        BuildSucceededDialog.setObjectName("BuildSucceededDialog")
        BuildSucceededDialog.resize(458, 29)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BuildSucceededDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(BuildSucceededDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(BuildSucceededDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(BuildSucceededDialog)
        QtCore.QMetaObject.connectSlotsByName(BuildSucceededDialog)

    def retranslateUi(self, BuildSucceededDialog):
        _translate = QtCore.QCoreApplication.translate
        BuildSucceededDialog.setWindowTitle(_translate("BuildSucceededDialog", "Building"))
        self.label.setText(_translate("BuildSucceededDialog", "Building..."))
        self.label_2.setText(_translate("BuildSucceededDialog", "Do Not close under any circumstances!"))
