# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/building.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuildingDialog(object):
    def setupUi(self, BuildingDialog):
        BuildingDialog.setObjectName("BuildingDialog")
        BuildingDialog.resize(458, 29)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BuildingDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(BuildingDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(BuildingDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(BuildingDialog)
        QtCore.QMetaObject.connectSlotsByName(BuildingDialog)

    def retranslateUi(self, BuildingDialog):
        _translate = QtCore.QCoreApplication.translate
        BuildingDialog.setWindowTitle(_translate("BuildingDialog", "Building"))
        self.label.setText(_translate("BuildingDialog", "Building..."))
        self.label_2.setText(_translate("BuildingDialog", "Do Not close under any circumstances!"))
