# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/confirm_delete.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfirmDeleteDialog(object):
    def setupUi(self, ConfirmDeleteDialog):
        ConfirmDeleteDialog.setObjectName("ConfirmDeleteDialog")
        ConfirmDeleteDialog.resize(403, 226)
        self.gridLayout = QtWidgets.QGridLayout(ConfirmDeleteDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ConfirmDeleteDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfirmDeleteDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ConfirmDeleteDialog)
        self.buttonBox.accepted.connect(ConfirmDeleteDialog.b_yes) # type: ignore
        self.buttonBox.rejected.connect(ConfirmDeleteDialog.b_no) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfirmDeleteDialog)

    def retranslateUi(self, ConfirmDeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDeleteDialog.setWindowTitle(_translate("ConfirmDeleteDialog", "Delete Confirmation"))
        self.label.setText(_translate("ConfirmDeleteDialog", "Are you sure you want to delete this build?"))
