# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/failed.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuildFailedDialog(object):
    def setupUi(self, BuildFailedDialog):
        BuildFailedDialog.setObjectName("BuildFailedDialog")
        BuildFailedDialog.resize(400, 29)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BuildFailedDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(BuildFailedDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(BuildFailedDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(BuildFailedDialog)
        QtCore.QMetaObject.connectSlotsByName(BuildFailedDialog)

    def retranslateUi(self, BuildFailedDialog):
        _translate = QtCore.QCoreApplication.translate
        BuildFailedDialog.setWindowTitle(_translate("BuildFailedDialog", "Build Failed"))
        self.label.setText(_translate("BuildFailedDialog", "Build Failed!"))
        self.label_2.setText(_translate("BuildFailedDialog", "Please Try Again Later."))
