# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.play_tab = QtWidgets.QWidget()
        self.play_tab.setObjectName("play_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.play_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b_play = QtWidgets.QPushButton(self.play_tab)
        self.b_play.setObjectName("b_play")
        self.gridLayout_2.addWidget(self.b_play, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.builds_list = QtWidgets.QListWidget(self.play_tab)
        self.builds_list.setObjectName("builds_list")
        self.gridLayout_2.addWidget(self.builds_list, 0, 0, 6, 1)
        self.b_view_buildjson = QtWidgets.QPushButton(self.play_tab)
        self.b_view_buildjson.setObjectName("b_view_buildjson")
        self.gridLayout_2.addWidget(self.b_view_buildjson, 3, 1, 1, 1)
        self.b_info = QtWidgets.QPushButton(self.play_tab)
        self.b_info.setObjectName("b_info")
        self.gridLayout_2.addWidget(self.b_info, 1, 1, 1, 1)
        self.b_delete = QtWidgets.QPushButton(self.play_tab)
        self.b_delete.setObjectName("b_delete")
        self.gridLayout_2.addWidget(self.b_delete, 2, 1, 1, 1)
        self.tab_widget.addTab(self.play_tab, "")
        self.build_new_tab = QtWidgets.QWidget()
        self.build_new_tab.setObjectName("build_new_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.build_new_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b_build_new = QtWidgets.QPushButton(self.build_new_tab)
        self.b_build_new.setObjectName("b_build_new")
        self.gridLayout_3.addWidget(self.b_build_new, 0, 1, 1, 1)
        self.b_repo_info = QtWidgets.QPushButton(self.build_new_tab)
        self.b_repo_info.setObjectName("b_repo_info")
        self.gridLayout_3.addWidget(self.b_repo_info, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.available_repos_list = QtWidgets.QListWidget(self.build_new_tab)
        self.available_repos_list.setObjectName("available_repos_list")
        self.gridLayout_3.addWidget(self.available_repos_list, 0, 0, 3, 1)
        self.tab_widget.addTab(self.build_new_tab, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionView_License = QtGui.QAction(MainWindow)
        self.actionView_License.setObjectName("actionView_License")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionView_License)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.b_play.clicked.connect(MainWindow.b_play_build) # type: ignore
        self.b_info.clicked.connect(MainWindow.b_build_info) # type: ignore
        self.b_delete.clicked.connect(MainWindow.b_delete_build) # type: ignore
        self.b_view_buildjson.clicked.connect(MainWindow.b_view_buildjson) # type: ignore
        self.b_build_new.clicked.connect(MainWindow.b_build_new) # type: ignore
        self.b_repo_info.clicked.connect(MainWindow.b_repo_info) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SM64LinuxLauncher-qt"))
        self.b_play.setText(_translate("MainWindow", "Play"))
        self.b_view_buildjson.setText(_translate("MainWindow", "View build.json"))
        self.b_info.setText(_translate("MainWindow", "Info"))
        self.b_delete.setText(_translate("MainWindow", "Delete"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.play_tab), _translate("MainWindow", "Play"))
        self.b_build_new.setText(_translate("MainWindow", "Build New"))
        self.b_repo_info.setText(_translate("MainWindow", "Info"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.build_new_tab), _translate("MainWindow", "Build New"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionView_License.setText(_translate("MainWindow", "View License"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
