# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/ui/select_baserom.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BaseromSelectDialog(object):
    def setupUi(self, BaseromSelectDialog):
        BaseromSelectDialog.setObjectName("BaseromSelectDialog")
        BaseromSelectDialog.resize(418, 155)
        self.gridLayout = QtWidgets.QGridLayout(BaseromSelectDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(BaseromSelectDialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(BaseromSelectDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(BaseromSelectDialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(BaseromSelectDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(BaseromSelectDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(BaseromSelectDialog)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.retranslateUi(BaseromSelectDialog)
        self.pushButton.clicked.connect(BaseromSelectDialog.select_baserom) # type: ignore
        self.pushButton_2.clicked.connect(BaseromSelectDialog.b_continue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BaseromSelectDialog)

    def retranslateUi(self, BaseromSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        BaseromSelectDialog.setWindowTitle(_translate("BaseromSelectDialog", "Select Base ROM"))
        self.comboBox.setItemText(0, _translate("BaseromSelectDialog", "USA (us)"))
        self.comboBox.setItemText(1, _translate("BaseromSelectDialog", "European PAL (eu)"))
        self.comboBox.setItemText(2, _translate("BaseromSelectDialog", "Japanese (jp)"))
        self.pushButton.setText(_translate("BaseromSelectDialog", "Browse"))
        self.pushButton_2.setText(_translate("BaseromSelectDialog", "Continue"))
        self.label.setText(_translate("BaseromSelectDialog", "Select A Base ROM"))
        self.label_2.setText(_translate("BaseromSelectDialog", "Select the Region"))
