# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/succeeded.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuildSucceededDialog(object):
    def setupUi(self, BuildSucceededDialog):
        BuildSucceededDialog.setObjectName("BuildSucceededDialog")
        BuildSucceededDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(BuildSucceededDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.l_succeeded = QtWidgets.QLabel(BuildSucceededDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.l_succeeded.setFont(font)
        self.l_succeeded.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_succeeded.setObjectName("l_succeeded")
        self.gridLayout.addWidget(self.l_succeeded, 0, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(BuildSucceededDialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)

        self.retranslateUi(BuildSucceededDialog)
        self.pushButton_2.clicked.connect(BuildSucceededDialog.dismiss) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BuildSucceededDialog)

    def retranslateUi(self, BuildSucceededDialog):
        _translate = QtCore.QCoreApplication.translate
        BuildSucceededDialog.setWindowTitle(_translate("BuildSucceededDialog", "Build Suceeded!"))
        self.l_succeeded.setText(_translate("BuildSucceededDialog", "Build Succeeded!"))
        self.pushButton_2.setText(_translate("BuildSucceededDialog", "Dismiss"))
