# Form implementation generated from reading ui file './SM64LinuxLauncher-qt/launcher/res/ui/view_json.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlainTextView(object):
    def setupUi(self, PlainTextView):
        PlainTextView.setObjectName("PlainTextView")
        PlainTextView.resize(518, 383)
        self.gridLayout = QtWidgets.QGridLayout(PlainTextView)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(PlainTextView)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(PlainTextView)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(PlainTextView)
        self.pushButton.clicked.connect(PlainTextView.b_ok) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PlainTextView)

    def retranslateUi(self, PlainTextView):
        _translate = QtCore.QCoreApplication.translate
        PlainTextView.setWindowTitle(_translate("PlainTextView", "View Plain Text"))
        self.pushButton.setText(_translate("PlainTextView", "Ok"))
